// AUTO-GENERATED by backend/scripts/extract_presets.py on 2026-08-10T19:14:37 — DO NOT EDIT BY HAND.
// Each row's audio file is bundled at /presets/<audio_filename>.
// Provenance: see ../../PRESETS_MANIFEST.txt

export interface Preset {
  /** Stable id from the MikCil dataset, also used as the audio filename stem. */
  id: string;
  driverId: string;
  racingNumber: number | null;
  grandPrix: string;
  sessionDate: string;
  messageTimestamp: string;
  /** Path served from /public, e.g. "/presets/<id>.wav" */
  audioUrl: string;
  /** Length of the audio in seconds, for the player duration display. */
  durationSeconds: number;
  /** Which OpenF1 path this clip resolved through on extraction day. */
  correlationMethod: "exact" | "fallback_early" | "fallback_mid" | "fallback_late";
  /** Lap number pinned on extraction day — used for the "EXACT MATCH" panel when method === 'exact' */
  expectedLapNumber: number | null;
  expectedLapDuration: number | null;
  /** What the emotion classifier returned when run on the full audio (just provenance — UI uses its own analysis). */
  emotionRawLabel: string;
  emotionScore: number;
}

export const PRESETS: Preset[] = [
  {
    id: "2023_Bahrain_Grand_Prix_CHALEC01_16_20230305_154208",
    driverId: "CHALEC01",
    racingNumber: 16,
    grandPrix: "2023 Bahrain Grand Prix",
    sessionDate: "2023-03-05",
    messageTimestamp: "2023-03-05T15:42:32.645Z",
    audioUrl: "/presets/2023_Bahrain_Grand_Prix_CHALEC01_16_20230305_154208.wav",
    durationSeconds: 16.4,
    correlationMethod: "exact",
    expectedLapNumber: 24,
    expectedLapDuration: 97.972,
    emotionRawLabel: "disgust",
    emotionScore: 0.139,
  },
  {
    id: "2023_Bahrain_Grand_Prix_GEORUS01_63_20230305_155430",
    driverId: "GEORUS01",
    racingNumber: 63,
    grandPrix: "2023 Bahrain Grand Prix",
    sessionDate: "2023-03-05",
    messageTimestamp: "2023-03-05T15:54:53.351Z",
    audioUrl: "/presets/2023_Bahrain_Grand_Prix_GEORUS01_63_20230305_155430.wav",
    durationSeconds: 3.7,
    correlationMethod: "exact",
    expectedLapNumber: 31,
    expectedLapDuration: 101.035,
    emotionRawLabel: "neutral",
    emotionScore: 0.138,
  },
  {
    id: "2023_Bahrain_Grand_Prix_LANNOR01_4_20230305_151548",
    driverId: "LANNOR01",
    racingNumber: 4,
    grandPrix: "2023 Bahrain Grand Prix",
    sessionDate: "2023-03-05",
    messageTimestamp: "2023-03-05T15:16:18.377Z",
    audioUrl: "/presets/2023_Bahrain_Grand_Prix_LANNOR01_4_20230305_151548.wav",
    durationSeconds: 4.8,
    correlationMethod: "exact",
    expectedLapNumber: 8,
    expectedLapDuration: 100.857,
    emotionRawLabel: "happy",
    emotionScore: 0.133,
  },
  {
    id: "2023_Bahrain_Grand_Prix_LEWHAM01_44_20230305_151725",
    driverId: "LEWHAM01",
    racingNumber: 44,
    grandPrix: "2023 Bahrain Grand Prix",
    sessionDate: "2023-03-05",
    messageTimestamp: "2023-03-05T15:18:01.187Z",
    audioUrl: "/presets/2023_Bahrain_Grand_Prix_LEWHAM01_44_20230305_151725.wav",
    durationSeconds: 3.0,
    correlationMethod: "exact",
    expectedLapNumber: 9,
    expectedLapDuration: 100.323,
    emotionRawLabel: "neutral",
    emotionScore: 0.138,
  },
];
